### ISSUE TITLE
Add support for Internet Archive

### ISSUE THREAD

**Issue by Skylion007** [anoadragon453/Writing.com-Story-Scraper#1]
It would be nice if this script would also be able to save stories from the internet archive as well. This way, some already deleted stories could be enjoyed and backed up from archive.org before they added the username requirement.

**Comment by Skylion007** [comment]
Unfortunately, it doesn't appear the writing.com records are complete so alas let's hope people back them up before they go down.

**Comment by anoadragon453** [comment]
Have you tried pointing it to an Internet Archive'd page of a story? I'm assuming the HTML is similar and thus it should scrape correctly.

That is however assuming that this scraper still works with the live version of the site, it hasn't been maintained and thus functionality may have stagnated.

**Comment by Skylion007** [comment]
Yeah I was able to get it working with modification. Unfortunately, the
Internet Archive didn't seem to archive any story greater than a depth of
five or so, so it ended up being a futile effort. All the more important
someone backups the rest of the stories using this script.

**Comment by anoadragon453** [comment]
Ah, well if you're willing to make a PR with the changes you made I'll happily merge them into the master branch.

**Comment by Skylion007** [comment]
Not sure if I should because it would need to parse the website differently
based on what year the archive referred to. Also, the script does not
appear to scrape the current site correctly unless I am doing something
wrong.
